### ISSUE TITLE
About number of modalities in input

### ISSUE THREAD

**Issue by Aamer98** [SebastianGer/WildfireSpreadTS#2]
Hey! I was wondering about the difference in the number of modalities (channels) in input mentioned in the paper and documentation, which is 23, and the channel dimension when loading the dataset, which is 40. Did I overlook or miss something here? Thanks!

**Comment by SebastianGer** [comment]
> Hey! I was wondering about the difference in the number of modalities (channels) in input mentioned in the paper and documentation, which is 23, and the channel dimension when loading the dataset, which is 40. Did I overlook or miss something here? Thanks!

Thanks for the question! The difference comes from one-hot-encoding the landcover class. In the raw data it's only an integer, but because it's a nominal variable, it seemed a lot more sensible to use one-hot-encoding when feeding it into the network. Additionally, the active fire is available once as a binary feature, once containing the detection times. If you call `FireSpreadDataset.map_channel_index_to_features`, you can get the list of all feature names, either with or without the expanded land cover classes, depending on the boolean argument you pass.
